title: Jordan "Heroic" Hunt
author: Jordan Hunt
name: jordanlhunt
email: jordanlhunt@g.austincc.edu
description: >
  Entry-level Software developer looking for employment in the games industry
theme: minima
minima:
  skin: solarized
  social_links:
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/jordanlhunt/",
      }
    - { platform: youtube, user_url: "www.youtube.com/@HeroicGameHobbyist" }
